{
 "title": "Operator_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Partikelsensor",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\r\n  |> filter(fn: (r) => r._field == \"OPC_PM_A\" or r._field == \"OPC_PM_B\" or r._field == \"OPC_PM_C\")\r\n  |> first()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  "
    }
   ]
  },
  {
   "title": "BME280",
   "type": "barchart",
   "description": "Feuchtigkeit, Temperatur und Luftdruck",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\r\n  |> filter(fn: (r) => r._field == \"BME280_Humidity\" or r._field == \"BME280_Pressure\" or r._field == \"BME280_Temperature\")\r\n  |> first()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  "
    }
   ]
  },
  {
   "title": "NDIR-1",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "import \"strings\"\r\nfrom(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r.nav_status == \"valid\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r._field, substr: \"-1\") == true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "NDIR-2",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "import \"strings\"\r\nfrom(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r.nav_status == \"valid\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r._field, substr: \"-2\") == true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "NDIR-3",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "import \"strings\"\r\nfrom(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r.nav_status == \"valid\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r._field, substr: \"-3\") == true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "NDIR-4",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "import \"strings\"\r\nfrom(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r.nav_status == \"valid\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r._field, substr: \"-4\") == true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> last()"
    }
   ]
  }
 ]
}