{
 "title": "SiSchaMo",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "altitudeVar",
    "label": "Altitude [m]",
    "query": "300, 500, 1000, 2000, 3000, 10000"
   }
  ]
 },
 "panels": [
  {
   "title": "Track",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\r\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"OPC_PM_Bin_2\" or r._field == \"altitude\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\", \"nav_status\"])\r\n  |> filter(fn: (r) => r.altitude <= ${altitudeVar})"
    }
   ]
  },
  {
   "title": "Altitude Selection [m]",
   "type": "volkovlabs-variable-panel",
   "description": "Selection of the altitude to be displayed.",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 19 }
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 4, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\r\n  |> filter(fn: (r) => r._field == \"OPC_PM_C\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\"])"
    }
   ]
  },
  {
   "title": "PM1.0",
   "type": "timeseries",
   "description": "Partikelsensor PM1 Werte",
   "gridPos": { "h": 10, "w": 15, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"sischamo\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\r\n  |> filter(fn: (r) => r._field == \"OPC_PM_A\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"type\"])"
    }
   ]
  }
 ]
}